---
title: 'STAT 6021: Final Project EDA'
author: "Group 1"
output:
  pdf_document: default
---

## Libraries

```{r}
library(tidyverse)
library(ggcorrplot)
```

## Data

Looking at sleep efficiency, with hours of sleep as the response variable

```{r}
sleep <- read.csv("Sleep_Efficiency.csv")

# Remove ID, bedtime, and wakeup time
sleep <- sleep[, -c(1, 4, 5)]
View(sleep)
```

```{r}
colnames(sleep)
```

## Cleaning

```{r}
# Turn percentages to proportions
sleep <- sleep %>% 
  mutate(REM.sleep.percentage = REM.sleep.percentage / 100,
         Deep.sleep.percentage = Deep.sleep.percentage / 100,
         Light.sleep.percentage = Light.sleep.percentage / 100)

# Weighted sleep (Sleep.duration * Sleep.efficiency)
sleep <- sleep %>% 
  mutate(weighted.sleep = Sleep.duration * Sleep.efficiency)
```

```{r}
str(sleep)
```

## Correlation Matrix

```{r}
sleep.num <- sleep[-c(2, 11)]
cor_mat<-round(cor(sleep.num),2)
ggcorrplot(cor_mat,lab=TRUE, type="lower", method="circle")
```

## Boxplots

### Alcohol Consumption

```{r}
ggplot(sleep, aes(x=as.factor(Alcohol.consumption), y=weighted.sleep, 
                  fill=as.factor(Alcohol.consumption)))+
  geom_boxplot(outlier.color="red")+geom_jitter()+
  labs(title = "Alcohol Consumption and Weighted Sleep Value",
       x="Amount of Alcohol (oz)", y = "Weighted Sleep Value", fill="Alcohol Consumption")
```

### Caffeine Consumption

```{r}
ggplot(sleep, aes(x=as.factor(Caffeine.consumption), y=weighted.sleep,
                  fill=as.factor(Caffeine.consumption)))+geom_boxplot(outlier.color="red")+geom_jitter()+
  labs(title = "Caffeine Consumption and Weighted Sleep Value",
       x="Amount of Caffeine (mg)", y = "Weighted Sleep Value", fill="Caffeine Consumption")
```

### Smoking Status

```{r}
ggplot(sleep, aes(x=as.factor(Smoking.status), y=weighted.sleep,
                  fill=as.factor(Smoking.status)))+geom_boxplot(outlier.color="red")+geom_jitter()+
  labs(title = "Smoking Status and Weighted Sleep Value",
       x="", y = "Weighted Sleep Value", fill="Smoking Status")
```

### Exercise Frequency

```{r}
ggplot(sleep, aes(x=as.factor(Exercise.frequency), y=weighted.sleep,
                  fill=as.factor(Exercise.frequency)))+geom_boxplot(outlier.color="red")+geom_jitter()+
  labs(title = "Exercise Frequency and Weighted Sleep Value",
       x="Number of Times Exercised per week", y = "Weighted Sleep Value", fill="Exercise Frequency")
```

## Distributions

```{r}
ggplot(sleep,aes(x=Sleep.duration))+
  geom_density()+
  labs(title = "Distribution of Sleep Duration",
       x = "Sleep Duration (hours)",
       y = "Density")
```

```{r}
ggplot(sleep,aes(x=Sleep.efficiency))+
  geom_density()+
  labs(title = "Distribution of Sleep Efficiency",
       x = "Sleep Efficiency",
       y = "Density")
```


```{r}
ggplot(sleep,aes(x=weighted.sleep))+
  geom_density()+
  labs(title = "Distribution of Weighted Sleep Value",
       x = "Weighted Sleep Value",
       y = "Density")
```

